baseURL = 'https://ramstetter.com'
languageCode = 'en-us'
title = 'ramstetter.com'
theme = 'mainroad'
enableEmoji = true

[Params]
	description = "system and embedded software engineer"
	copyright = "Rick Ramstetter. All rights reserved"

	opengraph = false
	schema = false
	twitter_cards = false
	authorbox = false
	toc = false
	pager = false
	
	post_meta = ["author", "date", "categories", "translations"]

	mainSections = []

	dateformat = "2006-01-02"

	mathjax = false

	footer_credits = "Test"

	customCSS = ["css/rick-ramstetter.css"]

	googleFontsLink = false

[Params.logo]
	image = "img/rick-ramstetter.webp"
	title = "Rick Ramstetter"
	subtitle = "system and embedded software engineer"

[Author]
 	name = "Rick Ramstetter"

[menus]
[[menus.main]]
	name = 'Main'
	pageref = '/'
	weight = 10

[[menus.main]]
	name = 'Posts'
	pageref = '/posts/'
	weight = 20

[[menus.main]]
	name = 'Contact'
	pageref = '/pages/contact/index.md'
	weight = 110

[[menus.main]]
	name = "Open Source"
	pageref = '/pages/open-source/index.md'
	weight = 40

[[menus.main]]
	name = 'Past Clients'
	pageref = '/pages/past-clients/index.md'
	weight = 50

[markup.goldmark.renderer]
  unsafe = true
