baseURL = 'https://ramstetter.com'
languageCode = 'en-us'
title = 'ramstetter.com'
theme = 'mainroad'
enableEmoji = true

[Params]
	description = "system and embedded software engineer"
	copyright = "Rick Ramstetter. All rights reserved"

	opengraph = false
	schema = false
	twitter_cards = false
	authorbox = false
	toc = false
	pager = false
	readmore = false
	
	post_meta = ["author", "date", "categories", "translations"]

	mainSections = ["posts"]

	dateformat = "2006-01-02"

	mathjax = false

	footer_credits = ""

	customCSS = ["css/rick-ramstetter.css"]

	googleFontsLink = false

[Params.logo]
	image = "img/rick-ramstetter.webp"
	title = "Rick Ramstetter"
	subtitle = "system and embedded software engineer"

[Author]
 	name = "Rick Ramstetter"

[markup.goldmark.renderer]
  unsafe = true
